package provider

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// CLI adapter — align-framebaker-providers tasks 3.2/3.3 (自定义 CLI Provider).
//
// A custom CLI provider runs a LOCAL executable chosen by the user; it never
// issues HTTP requests and never speaks a vendor protocol. The implementation
// is bound by design D5:
//
//   - argv, never a shell: the configured CLI fields (CLIPromptArg /
//     CLIOutputArg / CLIModelArg / CLIRefImageArg / CLIExtraArgs) are joined
//     into a Go argument slice and handed to exec.CommandContext. User values
//     (prompts with spaces/quotes, paths, model names) each stay ONE argv
//     element — no string interpolation into a shell command exists, so
//     special characters cannot change argument boundaries.
//   - Preflight before any process spawn: a missing command, empty prompt,
//     missing model, missing output argument, and references without a
//     configured reference-image argument are rejected with a readable
//     ConfigError BEFORE exec starts (零外呼 for the local boundary too).
//   - Reference images are written to private temp files (the tool receives
//     paths, not stdin), one "--ref <path>" pair per image in request order.
//   - The output file path is generated by this adapter (private temp dir) —
//     the user configures the OUTPUT FLAG, never the path, so a hostile
//     prompt cannot redirect writes.
//   - Failures are reported distinctly (task 3.3): executable not found,
//     non-zero exit code (with the tool's stderr tail), missing output file,
//     empty output, and invalid output format are separate readable errors.
//   - The legacy CLITemplate string is read-only compatibility input (task
//     3.4): it is preserved in settings and never executed.
//
// Text generation is not part of the CLI contract: the preset declares image
// only, matching DeclaredCapabilities(ProviderTypeCLI).

// cliRefKinds lists the reference-image kinds this adapter materializes as
// temp files. They mirror the kinds the HTTP adapters accept; anything else
// is rejected pre-flight instead of silently dropped.
const (
	cliRefKindReferenceImage = "reference_image"
	cliRefKindSprite         = "sprite"
)

// CLI is the custom CLI adapter for providers created from the FrameBaker
// 自定义 CLI preset (Type ProviderTypeCLI).
type CLI struct {
	cfg ProviderConfig
}

// NewCLI creates the CLI adapter. The HTTP client parameter is unused (the
// adapter spawns local processes, not HTTP calls); it is accepted so
// NewAdapter can construct every type through one signature.
func NewCLI(cfg ProviderConfig, _ *http.Client) *CLI {
	return &CLI{cfg: cfg}
}

func (c *CLI) ID() string { return c.cfg.ProviderID }

// Name returns the display name, falling back to the preset's vendor name.
func (c *CLI) Name() string {
	if n := strings.TrimSpace(c.cfg.Name); n != "" {
		return n
	}
	return "自定义 CLI"
}

// Capabilities mirrors DeclaredCapabilities(ProviderTypeCLI): image only —
// the CLI contract produces image assets; text/video stay undeclared.
func (c *CLI) Capabilities() Capabilities {
	return Capabilities{Image: true, Video: false, Text: false}
}

func (c *CLI) DefaultImageModel() string { return c.cfg.EffectiveModel() }

func (c *CLI) DefaultTextModel() string { return c.cfg.EffectiveTextModel() }

// buildCLIArgs assembles the exec argument slice (task 3.2: argv 构建). It is
// a pure function so the boundary tests can pin that spaces and special
// characters never cross an element boundary. Order: fixed extra args, prompt
// (flag or positional), model, reference images (flag repeated per image),
// output path last.
func buildCLIArgs(cfg ProviderConfig, prompt, model string, refPaths []string, outputPath string) []string {
	args := make([]string, 0, len(cfg.CLIExtraArgs)+2*len(refPaths)+6)
	args = append(args, cfg.CLIExtraArgs...)
	if flag := strings.TrimSpace(cfg.CLIPromptArg); flag != "" {
		args = append(args, flag, prompt)
	} else {
		args = append(args, prompt)
	}
	if flag := strings.TrimSpace(cfg.CLIModelArg); flag != "" && model != "" {
		args = append(args, flag, model)
	}
	for _, p := range refPaths {
		args = append(args, cfg.CLIRefImageArg, p)
	}
	args = append(args, strings.TrimSpace(cfg.CLIOutputArg), outputPath)
	return args
}

// GenerateImage runs the configured CLI once and returns the validated output
// image bytes. The context bounds the process: cancellation (user abort or
// the configured per-call timeout) kills the child process.
func (c *CLI) GenerateImage(ctx context.Context, req ImageRequest) (*ImageResult, error) {
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("provider %s: CLI generation cancelled before start: %w", c.ID(), err)
	}
	// The configured per-call timeout bounds the process even when the caller
	// passes a bare context (exec.CommandContext kills the child on expiry).
	ctx, cancel := applyTimeout(ctx, c.cfg.EffectiveTimeout())
	defer cancel()
	command := strings.TrimSpace(c.cfg.CLICommand)
	if command == "" {
		if strings.TrimSpace(c.cfg.CLITemplate) != "" {
			return nil, MarkNotRetryable(configErrf("provider %s: CLI command is not configured (cliTemplate is legacy read-only input; fill cliCommand instead)", c.ID()))
		}
		return nil, MarkNotRetryable(configErrf("provider %s: CLI command is not configured", c.ID()))
	}
	prompt := strings.TrimSpace(req.Prompt)
	if prompt == "" {
		return nil, configErrf("provider %s: prompt is required", c.ID())
	}
	model := ResolveModel(req.Model, c.cfg.EffectiveModel())
	if model == "" {
		return nil, configErrf("provider %s: image model is required (configure the model this CLI tool consumes)", c.ID())
	}
	if strings.TrimSpace(c.cfg.CLIOutputArg) == "" {
		return nil, MarkNotRetryable(configErrf("provider %s: CLI output parameter is not configured (fill the output flag, e.g. --output, so the generated file can be validated)", c.ID()))
	}

	// Reference images → private temp files (preflight: kind/data validated,
	// reference argument required). Every temp file is cleaned up on return.
	var refPaths []string
	defer func() {
		for _, p := range refPaths {
			_ = os.Remove(p)
		}
	}()
	if len(req.References) > 0 {
		if strings.TrimSpace(c.cfg.CLIRefImageArg) == "" {
			return nil, MarkNotRetryable(configErrf("provider %s: reference images were attached but the CLI reference-image parameter is not configured (fill the reference flag, e.g. --ref, or drop the references)", c.ID()))
		}
		for i, ref := range req.References {
			if ref.Kind != cliRefKindReferenceImage && ref.Kind != cliRefKindSprite {
				return nil, configErrf("provider %s: reference %d has unsupported kind %q (use reference_image or sprite)", c.ID(), i, ref.Kind)
			}
			if len(ref.Data) == 0 {
				return nil, configErrf("provider %s: reference %d is empty", c.ID(), i)
			}
			f, err := os.CreateTemp("", "oframe-cli-ref-*.png")
			if err != nil {
				return nil, fmt.Errorf("provider %s: create reference temp file: %w", c.ID(), err)
			}
			path := f.Name()
			if _, err := f.Write(ref.Data); err != nil {
				f.Close()
				_ = os.Remove(path)
				return nil, fmt.Errorf("provider %s: write reference temp file: %w", c.ID(), err)
			}
			if err := f.Close(); err != nil {
				_ = os.Remove(path)
				return nil, fmt.Errorf("provider %s: close reference temp file: %w", c.ID(), err)
			}
			refPaths = append(refPaths, path)
		}
	}

	// The output path is generated here (private temp dir, removed on return):
	// prompts can never redirect the tool's writes.
	outDir, err := os.MkdirTemp("", "oframe-cli-out-")
	if err != nil {
		return nil, fmt.Errorf("provider %s: create output temp dir: %w", c.ID(), err)
	}
	defer os.RemoveAll(outDir)
	outPath := filepath.Join(outDir, "output.png")

	args := buildCLIArgs(c.cfg, prompt, model, refPaths, outPath)
	cmd := exec.CommandContext(ctx, command, args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			return nil, fmt.Errorf("provider %s: CLI generation cancelled: %w", c.ID(), ctxErr)
		}
		var exitErr *exec.ExitError
		switch {
		case errors.As(err, &exitErr):
			return nil, fmt.Errorf("provider %s: CLI exited with code %d: %s", c.ID(), exitErr.ExitCode(), truncate(stderr.String(), 500))
		case errors.Is(err, exec.ErrNotFound) || errors.Is(err, fs.ErrNotExist):
			return nil, MarkNotRetryable(fmt.Errorf("provider %s: CLI executable not found: %q", c.ID(), command))
		default:
			return nil, fmt.Errorf("provider %s: CLI failed to start: %w", c.ID(), err)
		}
	}

	data, mime, err := readCLIOutput(outPath)
	if err != nil {
		return nil, fmt.Errorf("provider %s: %w", c.ID(), err)
	}
	return &ImageResult{Data: data, MIME: mime, Provider: c.ID(), Model: model}, nil
}

// GenerateText is unsupported: the CLI preset declares image only and the CLI
// contract has no text surface. The refusal is purely local (zero spawns).
func (c *CLI) GenerateText(context.Context, TextRequest) (*TextResult, error) {
	return nil, MarkNotRetryable(fmt.Errorf(
		"provider %s does not support text generation (the CLI adapter executes image tools only): %w; %w",
		c.ID(), ErrCapabilityUnsupported, ErrUnsupported))
}

// readCLIOutput validates the produced file (task 3.3): missing, empty,
// oversized and non-image outputs each fail with a distinct readable error.
func readCLIOutput(path string) ([]byte, string, error) {
	f, err := os.Open(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, "", fmt.Errorf("CLI exited successfully but did not produce the output file %q", path)
		}
		return nil, "", fmt.Errorf("open CLI output file: %w", err)
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil {
		return nil, "", fmt.Errorf("stat CLI output file: %w", err)
	}
	if info.Size() == 0 {
		return nil, "", fmt.Errorf("CLI output file %q is empty", path)
	}
	data, err := readCappedBody(f, maxGenerationResponseBytes, "CLI output")
	if err != nil {
		return nil, "", fmt.Errorf("read CLI output file: %w", err)
	}
	mime := sniffImageFormat(data)
	if mime == "" {
		return nil, "", fmt.Errorf("CLI output file %q is not a valid image (PNG/JPEG/GIF/WebP expected)", path)
	}
	return data, mime, nil
}

// sniffImageFormat identifies a generated image by magic bytes. It returns ""
// for anything it cannot recognize (reported as an invalid-format failure).
func sniffImageFormat(b []byte) string {
	switch {
	case len(b) >= 8 && bytes.Equal(b[:8], []byte{0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A}):
		return "image/png"
	case len(b) >= 3 && b[0] == 0xFF && b[1] == 0xD8 && b[2] == 0xFF:
		return "image/jpeg"
	case len(b) >= 6 && (string(b[:6]) == "GIF87a" || string(b[:6]) == "GIF89a"):
		return "image/gif"
	case len(b) >= 12 && string(b[0:4]) == "RIFF" && string(b[8:12]) == "WEBP":
		return "image/webp"
	}
	return ""
}
