// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {assetexport} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function CandidateConsistency(arg1:boolean):Promise<main.ConsistencyScoreView>;

export function CandidateDecide(arg1:string,arg2:boolean,arg3:string):Promise<main.AcceptanceDecisionView>;

export function CandidateHistory():Promise<Array<main.CandidateHistoryView>>;

export function CurrentAssets():Promise<Array<main.AcceptedAssetView>>;

export function CurrentPackage():Promise<main.PackageSummary>;

export function DirectionPreview(arg1:string,arg2:string):Promise<main.CandidatePreviewView>;

export function EditDirection(arg1:string,arg2:string,arg3:Array<main.EditInstructionView>):Promise<main.EditResultView>;

export function EnhanceSettingsGet():Promise<main.EnhanceSettingsView>;

export function EnhanceSettingsSet(arg1:string,arg2:string):Promise<void>;

export function ExportCreate(arg1:string,arg2:string,arg3:string):Promise<assetexport.Result>;

export function ExportHistory():Promise<Array<assetexport.HistoryRecord>>;

export function ExportValidate(arg1:string):Promise<void>;

export function GenerationPlanConfirm(arg1:string,arg2:boolean):Promise<main.GenerationResultView>;

export function GenerationPlanGet(arg1:string):Promise<main.GenerationPlanView>;

export function GenerationPlanPrepare(arg1:main.GenerationRequestView):Promise<main.GenerationPlanView>;

export function IdentityAddAnchor(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.AnchorView>;

export function IdentityAddAnchorPreset(arg1:string,arg2:string):Promise<main.AnchorView>;

export function IdentityAnchorPresets():Promise<Array<main.AnchorPresetView>>;

export function IdentityGet():Promise<main.IdentityView>;

export function IdentityImportMaterial(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.MaterialView>;

export function IdentityRename(arg1:string,arg2:string):Promise<void>;

export function IdentitySetCanvas(arg1:number,arg2:number):Promise<void>;

export function IdentitySetCategory(arg1:string,arg2:string):Promise<void>;

export function IdentitySetDescription(arg1:string):Promise<void>;

export function MotionCreate(arg1:string,arg2:number,arg3:boolean):Promise<main.MotionView>;

export function MotionGet(arg1:string):Promise<main.MotionView>;

export function MotionList():Promise<Array<main.MotionView>>;

export function MotionPlaybackTempo(arg1:string,arg2:string):Promise<Array<number>>;

export function MotionSetFrameDurations(arg1:string,arg2:string,arg3:Array<number>):Promise<main.MotionView>;

export function MotionSetStrategy(arg1:string,arg2:number,arg3:boolean):Promise<main.MotionView>;

export function OperationLog():Promise<Array<main.OperationLogEntryView>>;

export function PackageClose():Promise<void>;

export function PackageCreate(arg1:string,arg2:string):Promise<main.PackageSummary>;

export function PackageDelete(arg1:string):Promise<void>;

export function PackageOpen(arg1:string):Promise<main.PackageSummary>;

export function PickMaterialFile(arg1:string):Promise<string>;

export function PickWorkspaceDir(arg1:string):Promise<string>;

export function PresetCatalog():Promise<main.PresetCatalogView>;

export function ProviderAdd(arg1:main.ProviderConfigView):Promise<main.ProviderInfoView>;

export function ProviderConfigGet(arg1:string):Promise<main.ProviderConfigView>;

export function ProviderConfigSave(arg1:string,arg2:main.ProviderConfigView):Promise<void>;

export function ProviderList():Promise<Array<main.ProviderInfoView>>;

export function ProviderModels(arg1:string):Promise<Array<string>>;

export function ProviderModelsDraft(arg1:main.ProviderConfigView):Promise<Array<string>>;

export function ProviderOptions(arg1:string):Promise<Array<main.ProviderOptionView>>;

export function ProviderPresets():Promise<Array<main.ProviderPresetView>>;

export function ProviderRemove(arg1:string):Promise<void>;

export function ProviderSetActive(arg1:string):Promise<void>;

export function ProviderStats():Promise<main.StatsView>;

export function ProviderTest(arg1:string):Promise<main.ProviderTestView>;

export function ProviderTestDraft(arg1:main.ProviderConfigView):Promise<main.ProviderTestView>;

export function ProviderValidate(arg1:string):Promise<string>;

export function RollbackTo(arg1:number):Promise<Array<main.OperationLogEntryView>>;

export function TaskAbandon(arg1:string):Promise<void>;

export function TaskGet(arg1:string):Promise<main.TaskSummary>;

export function TaskList():Promise<Array<main.TaskSummary>>;

export function TaskResumeAll():Promise<number>;

export function TaskRetry(arg1:string):Promise<void>;

export function VideoExtractionConfig(arg1:string):Promise<main.VideoExtractionConfigView>;

export function WorkspaceEnsureDefault():Promise<main.WorkspaceInfo>;

export function WorkspaceList():Promise<Array<main.PackageSummary>>;

export function WorkspaceMigrate(arg1:string,arg2:boolean):Promise<main.WorkspaceInfo>;

export function WorkspaceOpen(arg1:string):Promise<main.WorkspaceInfo>;

export function WorkspacePath():Promise<string>;
