// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function CandidateConsistency(arg1) {
  return window['go']['main']['App']['CandidateConsistency'](arg1);
}

export function CandidateDecide(arg1, arg2, arg3) {
  return window['go']['main']['App']['CandidateDecide'](arg1, arg2, arg3);
}

export function CandidateHistory() {
  return window['go']['main']['App']['CandidateHistory']();
}

export function CurrentAssets() {
  return window['go']['main']['App']['CurrentAssets']();
}

export function CurrentPackage() {
  return window['go']['main']['App']['CurrentPackage']();
}

export function DirectionPreview(arg1, arg2) {
  return window['go']['main']['App']['DirectionPreview'](arg1, arg2);
}

export function EditDirection(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditDirection'](arg1, arg2, arg3);
}

export function EnhanceSettingsGet() {
  return window['go']['main']['App']['EnhanceSettingsGet']();
}

export function EnhanceSettingsSet(arg1, arg2) {
  return window['go']['main']['App']['EnhanceSettingsSet'](arg1, arg2);
}

export function ExportCreate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportCreate'](arg1, arg2, arg3);
}

export function ExportHistory() {
  return window['go']['main']['App']['ExportHistory']();
}

export function ExportValidate(arg1) {
  return window['go']['main']['App']['ExportValidate'](arg1);
}

export function GenerationPlanConfirm(arg1, arg2) {
  return window['go']['main']['App']['GenerationPlanConfirm'](arg1, arg2);
}

export function GenerationPlanGet(arg1) {
  return window['go']['main']['App']['GenerationPlanGet'](arg1);
}

export function GenerationPlanPrepare(arg1) {
  return window['go']['main']['App']['GenerationPlanPrepare'](arg1);
}

export function IdentityAddAnchor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['IdentityAddAnchor'](arg1, arg2, arg3, arg4);
}

export function IdentityAddAnchorPreset(arg1, arg2) {
  return window['go']['main']['App']['IdentityAddAnchorPreset'](arg1, arg2);
}

export function IdentityAnchorPresets() {
  return window['go']['main']['App']['IdentityAnchorPresets']();
}

export function IdentityGet() {
  return window['go']['main']['App']['IdentityGet']();
}

export function IdentityImportMaterial(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['IdentityImportMaterial'](arg1, arg2, arg3, arg4);
}

export function IdentityRename(arg1, arg2) {
  return window['go']['main']['App']['IdentityRename'](arg1, arg2);
}

export function IdentitySetCanvas(arg1, arg2) {
  return window['go']['main']['App']['IdentitySetCanvas'](arg1, arg2);
}

export function IdentitySetCategory(arg1, arg2) {
  return window['go']['main']['App']['IdentitySetCategory'](arg1, arg2);
}

export function IdentitySetDescription(arg1) {
  return window['go']['main']['App']['IdentitySetDescription'](arg1);
}

export function MotionCreate(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionCreate'](arg1, arg2, arg3);
}

export function MotionGet(arg1) {
  return window['go']['main']['App']['MotionGet'](arg1);
}

export function MotionList() {
  return window['go']['main']['App']['MotionList']();
}

export function MotionPlaybackTempo(arg1, arg2) {
  return window['go']['main']['App']['MotionPlaybackTempo'](arg1, arg2);
}

export function MotionSetFrameDurations(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionSetFrameDurations'](arg1, arg2, arg3);
}

export function MotionSetStrategy(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionSetStrategy'](arg1, arg2, arg3);
}

export function OperationLog() {
  return window['go']['main']['App']['OperationLog']();
}

export function PackageClose() {
  return window['go']['main']['App']['PackageClose']();
}

export function PackageCreate(arg1, arg2) {
  return window['go']['main']['App']['PackageCreate'](arg1, arg2);
}

export function PackageDelete(arg1) {
  return window['go']['main']['App']['PackageDelete'](arg1);
}

export function PackageOpen(arg1) {
  return window['go']['main']['App']['PackageOpen'](arg1);
}

export function PickMaterialFile(arg1) {
  return window['go']['main']['App']['PickMaterialFile'](arg1);
}

export function PickWorkspaceDir(arg1) {
  return window['go']['main']['App']['PickWorkspaceDir'](arg1);
}

export function PresetCatalog() {
  return window['go']['main']['App']['PresetCatalog']();
}

export function ProviderAdd(arg1) {
  return window['go']['main']['App']['ProviderAdd'](arg1);
}

export function ProviderConfigGet(arg1) {
  return window['go']['main']['App']['ProviderConfigGet'](arg1);
}

export function ProviderConfigSave(arg1, arg2) {
  return window['go']['main']['App']['ProviderConfigSave'](arg1, arg2);
}

export function ProviderList() {
  return window['go']['main']['App']['ProviderList']();
}

export function ProviderModels(arg1) {
  return window['go']['main']['App']['ProviderModels'](arg1);
}

export function ProviderModelsDraft(arg1) {
  return window['go']['main']['App']['ProviderModelsDraft'](arg1);
}

export function ProviderOptions(arg1) {
  return window['go']['main']['App']['ProviderOptions'](arg1);
}

export function ProviderPresets() {
  return window['go']['main']['App']['ProviderPresets']();
}

export function ProviderRemove(arg1) {
  return window['go']['main']['App']['ProviderRemove'](arg1);
}

export function ProviderSetActive(arg1) {
  return window['go']['main']['App']['ProviderSetActive'](arg1);
}

export function ProviderStats() {
  return window['go']['main']['App']['ProviderStats']();
}

export function ProviderTest(arg1) {
  return window['go']['main']['App']['ProviderTest'](arg1);
}

export function ProviderTestDraft(arg1) {
  return window['go']['main']['App']['ProviderTestDraft'](arg1);
}

export function ProviderValidate(arg1) {
  return window['go']['main']['App']['ProviderValidate'](arg1);
}

export function RollbackTo(arg1) {
  return window['go']['main']['App']['RollbackTo'](arg1);
}

export function TaskAbandon(arg1) {
  return window['go']['main']['App']['TaskAbandon'](arg1);
}

export function TaskGet(arg1) {
  return window['go']['main']['App']['TaskGet'](arg1);
}

export function TaskList() {
  return window['go']['main']['App']['TaskList']();
}

export function TaskResumeAll() {
  return window['go']['main']['App']['TaskResumeAll']();
}

export function TaskRetry(arg1) {
  return window['go']['main']['App']['TaskRetry'](arg1);
}

export function VideoExtractionConfig(arg1) {
  return window['go']['main']['App']['VideoExtractionConfig'](arg1);
}

export function WorkspaceEnsureDefault() {
  return window['go']['main']['App']['WorkspaceEnsureDefault']();
}

export function WorkspaceList() {
  return window['go']['main']['App']['WorkspaceList']();
}

export function WorkspaceMigrate(arg1, arg2) {
  return window['go']['main']['App']['WorkspaceMigrate'](arg1, arg2);
}

export function WorkspaceOpen(arg1) {
  return window['go']['main']['App']['WorkspaceOpen'](arg1);
}

export function WorkspacePath() {
  return window['go']['main']['App']['WorkspacePath']();
}
